local parsers = {
    "astro",
    "bash",
    "c",
    "c_sharp",
    "css",
    "dockerfile",
    "gitattributes",
    "gitignore",
    "go",
    "graphql",
    "haskell",
    "hcl",
    "html",
    "hurl",
    "java",
    "javascript",
    "json",
    "kotlin",
    "latex",
    "lua",
    "markdown",
    "markdown_inline",
    "php",
    "python",
    "prisma",
    "regex",
    "rust",
    "scss",
    "sql",
    "terraform",
    "toml",
    "tsx",
    "typescript",
    "vue",
    "yaml",
}

return {
    {
        "nvim-treesitter/nvim-treesitter",
        lazy = false,
        build = ":TSUpdate",
        config = function()
            require("nvim-treesitter").install(parsers):wait(300000) -- wait max. 5 minutes
        end,
    },
}
